/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
  'excerpt' : string,
  'category' : string,
}
export interface ContactMessage {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface _SERVICE {
  'createPost' : ActorMethod<[string, string, string, string], bigint>,
  'deletePost' : ActorMethod<[bigint], boolean>,
  'getAllMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllPosts' : ActorMethod<[], Array<BlogPost>>,
  'getPostById' : ActorMethod<[bigint], [] | [BlogPost]>,
  'submitContactMessage' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];