/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deletePost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getPostById' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
  'submitLead' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deletePost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getPostById' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
    'submitLead' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };